version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn project5.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:

      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_prod

  pgadmin:
    container_name: pgadmin4_container_prod
    image: dpage/pgadmin4
    restart: always
    environment:
      - ./.env.prod.db


    ports:
      - "5050:80"
volumes:
  postgres_data: