# Generated by Django 3.1.5 on 2022-01-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20220101_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Mypost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_comment',
            new_name='mypost_comment',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='post_owner',
            new_name='mypost_owner',
        ),
    ]
