# Generated by Django 3.1.5 on 2022-01-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed',
        ),
    ]
