# Generated by Django 3.1.5 on 2022-01-17 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank='TRUE', related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
