# Generated by Django 3.1.5 on 2022-02-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0002_auto_20220213_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='passenger',
        ),
    ]
