# Generated by Django 3.1.5 on 2022-02-20 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0004_route_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank='FALSE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
