# Generated by Django 3.1.5 on 2022-03-07 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0005_auto_20220307_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 7, 16, 59, 58, 729358, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 7, 16, 59, 58, 729358, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
