# Generated by Django 3.1.5 on 2022-02-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0005_auto_20220220_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='route',
            name='passenger',
        ),
        migrations.AddField(
            model_name='route',
            name='thedriver',
            field=models.ForeignKey(blank='FALSE', null='FALSE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default='FALSE',
        ),
        migrations.AddField(
            model_name='route',
            name='thepassenger',
            field=models.ManyToManyField(blank='TRUE', null='TRUE', related_name='routes', to=settings.AUTH_USER_MODEL),
            preserve_default='TRUE',
        ),
    ]
