# Generated by Django 3.1.5 on 2022-02-20 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0006_auto_20220220_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='thepassenger',
        ),
        migrations.AddField(
            model_name='route',
            name='thepassenger',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to=settings.AUTH_USER_MODEL),
            preserve_default='TRUE',
        ),
    ]
