# Generated by Django 3.1.5 on 2022-02-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0007_auto_20220220_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='thepassenger',
        ),
    ]
