# Generated by Django 3.1.5 on 2022-02-20 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0008_remove_route_thepassenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 2, 20), verbose_name='date orig'),
        ),
        migrations.AddField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 2, 20, 18, 45, 42, 121925, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AddField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 2, 20, 18, 45, 42, 121925, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
