# Generated by Django 3.1.5 on 2022-03-25 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0013_auto_20220322_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fin_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 3, 25), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 25, 19, 4, 53, 474474, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 25, 19, 4, 53, 474474, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
