# Generated by Django 3.1.5 on 2022-03-25 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0014_auto_20220325_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='fin_mark',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 25, 21, 11, 14, 340852, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 25, 21, 11, 14, 340852, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
