# Generated by Django 3.1.5 on 2022-03-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0015_auto_20220325_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='date_orig',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='map_pic',
        ),
        migrations.RemoveField(
            model_name='route',
            name='no_pass',
        ),
        migrations.RemoveField(
            model_name='route',
            name='thedriver',
        ),
        migrations.RemoveField(
            model_name='route',
            name='thepassenger',
        ),
        migrations.RemoveField(
            model_name='route',
            name='time_dep',
        ),
        migrations.RemoveField(
            model_name='route',
            name='time_orig',
        ),
    ]
