# Generated by Django 3.1.5 on 2022-04-09 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0016_auto_20220327_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='message',
            field=models.ManyToManyField(blank='TRUE', related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 4, 9), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 13, 8, 56, 988464, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 13, 8, 56, 988464, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
