# Generated by Django 3.1.5 on 2022-04-11 16:32

import Capstone.models
import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0019_auto_20220411_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 11, 16, 32, 42, 339166, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 11, 16, 32, 42, 339166, tzinfo=utc), verbose_name='time orig'),
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=Capstone.models.random_string, max_length=12)),
                ('passenger', models.ManyToManyField(blank='TRUE', related_name='passengers', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ManyToManyField(blank='TRUE', related_name='trips', to='Capstone.Route')),
            ],
        ),
    ]
