# Generated by Django 3.1.5 on 2022-04-09 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0019_auto_20220409_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 14, 29, 37, 769343, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 14, 29, 37, 769343, tzinfo=utc), verbose_name='time orig'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank='True', max_length=150)),
                ('recipient', models.ManyToManyField(blank='TRUE', related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
