# Generated by Django 3.1.5 on 2022-04-11 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0020_auto_20220411_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='passenger',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='passenger',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default='TRUE',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='trip',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='trip',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='Capstone.route'),
            preserve_default='TRUE',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 11, 16, 45, 25, 297594, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 11, 16, 45, 25, 297594, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
