# Generated by Django 3.1.5 on 2022-04-09 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0020_auto_20220409_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank='True', max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recipient', models.ManyToManyField(blank='TRUE', related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 14, 53, 22, 898092, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 14, 53, 22, 898092, tzinfo=utc), verbose_name='time orig'),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
