# Generated by Django 3.1.5 on 2022-04-09 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0023_auto_20220409_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='route_id',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 15, 52, 43, 765442, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 15, 52, 43, 765442, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
