# Generated by Django 3.1.5 on 2022-04-12 14:42

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0024_auto_20220412_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='passenger',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='passenger',
            field=models.ManyToManyField(blank='TRUE', related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 12, 14, 42, 23, 610059, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 12, 14, 42, 23, 610059, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
