# Generated by Django 3.1.5 on 2022-04-12 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0026_auto_20220412_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='trip',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='trip',
            field=models.ManyToManyField(blank='TRUE', related_name='trips', to='Capstone.Route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 12, 16, 4, 40, 405253, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 12, 16, 4, 40, 405253, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
