# Generated by Django 3.1.5 on 2021-04-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210411_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='price',
        ),
    ]
