# Generated by Django 3.1.5 on 2021-04-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210404_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='no category', max_length=150),
        ),
    ]
