# Generated by Django 3.1.5 on 2021-04-11 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210411_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(blank='TRUE', related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
