# Generated by Django 3.1.5 on 2021-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_comment',
            field=models.ManyToManyField(blank='TRUE', null='TRUE', related_name='listcomms', to='auctions.Listing'),
            preserve_default='TRUE',
        ),
    ]
