# Generated by Django 3.1.5 on 2021-04-04 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210404_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
