# Generated by Django 3.1.5 on 2021-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210414_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listing_comment',
            field=models.ManyToManyField(blank='TRUE', related_name='listcomms', to='auctions.Listing'),
        ),
    ]
