# Generated by Django 3.1.5 on 2021-04-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pic',
            new_name='picture_url',
        ),
    ]
