# Generated by Django 3.1.5 on 2021-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210414_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listcomms',
        ),
        migrations.AddField(
            model_name='comment',
            name='comms',
            field=models.ManyToManyField(blank='TRUE', related_name='comms', to='auctions.Listing'),
        ),
    ]
