# Generated by Django 3.1.5 on 2021-04-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210414_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comms',
            new_name='lists',
        ),
    ]
