# Generated by Django 3.1.5 on 2021-04-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210414_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lists',
        ),
        migrations.AddField(
            model_name='comment',
            name='lists',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='auctions.listing'),
            preserve_default='TRUE',
        ),
    ]
