# Generated by Django 3.1.5 on 2021-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210414_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lists',
        ),
        migrations.AddField(
            model_name='comment',
            name='lists',
            field=models.ManyToManyField(blank='TRUE', related_name='comms', to='auctions.Listing'),
        ),
    ]
