# Generated by Django 3.1.5 on 2021-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210418_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
