# Generated by Django 3.1.5 on 2021-04-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='auction',
        ),
        migrations.AddField(
            model_name='listing',
            name='closed_auction',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
