# Generated by Django 3.1.5 on 2021-04-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210418_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_message',
            field=models.CharField(blank='TRUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
