# Generated by Django 3.1.5 on 2021-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210419_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watching',
        ),
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(blank='TRUE', related_name='watchlist', to='auctions.Listing'),
        ),
    ]
