# Generated by Django 3.1.5 on 2022-01-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220102_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypost',
            old_name='mypost_owner',
            new_name='owner',
        ),
    ]
