# Generated by Django 3.1.5 on 2022-01-12 18:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_reply_lists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank='TRUE', related_name='followlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
