# Generated by Django 3.1.5 on 2022-01-17 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='likes',
            field=models.ManyToManyField(blank='TRUE', related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank='TRUE', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
