# Generated by Django 3.1.5 on 2022-03-07 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0004_auto_20220307_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='route_id',
            new_name='route_comm',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 7, 13, 36, 48, 268924, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 7, 13, 36, 48, 268924, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
