# Generated by Django 3.1.5 on 2022-03-13 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0008_auto_20220313_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='origin',
            new_name='departure',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 13, 19, 0, 6, 192464, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 13, 19, 0, 6, 192464, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
