# Generated by Django 3.1.5 on 2022-03-22 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0011_auto_20220322_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 22, 17, 4, 47, 767910, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 22, 17, 4, 47, 767910, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
