# Generated by Django 3.1.5 on 2022-03-27 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0015_auto_20220327_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 3, 27, 18, 18, 55, 393667, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 3, 27, 18, 18, 55, 393667, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
