# Generated by Django 3.1.5 on 2022-04-10 07:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0016_auto_20220327_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 4, 10), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 10, 7, 5, 57, 523039, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 10, 7, 5, 57, 523039, tzinfo=utc), verbose_name='time orig'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank='True', max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('route_id', models.IntegerField()),
                ('recipients', models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
