# Generated by Django 3.1.5 on 2022-04-10 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0017_auto_20220410_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipients',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 10, 7, 20, 38, 646259, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 10, 7, 20, 38, 646259, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
