# Generated by Django 3.1.5 on 2022-04-11 05:09

import Capstone.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0018_auto_20220410_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='keynum',
            field=models.CharField(default=Capstone.models.random_string, max_length=12),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 4, 11), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 11, 5, 9, 45, 122566, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 11, 5, 9, 45, 122566, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
