# Generated by Django 3.1.5 on 2022-04-12 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0021_auto_20220411_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='passenger',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qrpassenger',
            field=models.ManyToManyField(blank='TRUE', related_name='qrpassengers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='trip',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='trip',
            field=models.ManyToManyField(blank='TRUE', related_name='trips', to='Capstone.Route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 4, 12), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 12, 13, 20, 33, 827385, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 12, 13, 20, 33, 827385, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
