# Generated by Django 3.1.5 on 2022-04-13 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0025_auto_20220412_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='trip',
            field=models.ManyToManyField(related_name='qrcodes', to='Capstone.Route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 4, 13), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 13, 13, 44, 7, 689848, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 13, 13, 44, 7, 689848, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
