# Generated by Django 3.1.5 on 2022-04-28 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0027_auto_20220413_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='dist',
            field=models.FloatField(blank='TRUE', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 4, 28), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 16, 20, 22, 501375, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 16, 20, 22, 501375, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
