# Generated by Django 3.1.5 on 2022-04-28 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0028_auto_20220428_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 16, 37, 25, 112192, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 16, 37, 25, 112192, tzinfo=utc), verbose_name='time orig'),
        ),
    ]
