# Generated by Django 3.1.5 on 2022-06-11 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0043_auto_20220605_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='d_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(default=datetime.date(2022, 6, 11), verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(default=datetime.datetime(2022, 6, 11, 9, 46, 55, 90612, tzinfo=utc), verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(default=datetime.datetime(2022, 6, 11, 9, 46, 55, 90612, tzinfo=utc), verbose_name='time orig'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 6, 11)),
        ),
    ]
