# Generated by Django 3.1.5 on 2022-06-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0045_auto_20220612_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateTimeField(verbose_name='date orig'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_dep',
            field=models.TimeField(verbose_name='time dep'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_orig',
            field=models.TimeField(verbose_name='time orig'),
        ),
    ]
