# Generated by Django 3.1.5 on 2022-06-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0046_auto_20220612_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='d_a',
        ),
    ]
