# Generated by Django 3.1.5 on 2022-06-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0047_remove_route_d_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_orig',
            field=models.DateField(verbose_name='date orig'),
        ),
    ]
