# Generated by Django 3.1.5 on 2022-06-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0048_auto_20220612_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='d_a',
            field=models.BooleanField(default=False),
        ),
    ]
