# Generated by Django 3.1.5 on 2022-06-12 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0049_route_d_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 21, 4, 43, 57313), editable=False),
        ),
    ]
