# Generated by Django 3.1.5 on 2022-06-12 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0050_auto_20220612_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
