# Generated by Django 3.1.5 on 2022-06-13 17:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0051_auto_20220612_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date_ret',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date ret'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 6, 13)),
        ),
    ]
