# Generated by Django 3.1.5 on 2022-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0052_auto_20220613_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_ret',
            field=models.DateField(verbose_name='date ret'),
        ),
    ]
