# Generated by Django 3.1.5 on 2023-08-14 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0053_auto_20220613_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 8, 14)),
        ),
    ]
