# Generated by Django 3.1.5 on 2023-08-16 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0055_auto_20230815_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
    ]
