# Generated by Django 3.1.5 on 2021-04-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210414_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listcomms',
            field=models.ManyToManyField(blank='TRUE', related_name='listcomms', to='auctions.Listing'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_comment',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default='TRUE',
        ),
    ]
